name: LBOZO Workflow

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  LBOZO-Build:

#    runs-on: ${{ matrix.os }}
#    strategy:
#      fail-fast: false
#      matrix:
#        os: [ubuntu-latest, windows-latest, macOS-latest]
#        python-version: [3.6, 3.7]

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade black
        pip install -U pyinstaller
    - name: Black
      run: |
        black ./LBOZO/*.py --diff --check
        black ./LBOZO/src/*.py --diff --check
        black ./LBOZO/server/*.py --diff --check
    - name: Build and Compile
      run: |
        python3 -m PyInstaller -F --clean ./LBOZO/src/encrypt.py -n LBOZO
        python3 -m PyInstaller -F --clean ./LBOZO/src/decrypt.py -n LBOZO